import '../modelos/accion_bingo.dart';
import '../modelos/deporte.dart';

List<AccionBingo> _acciones(String prefijo, List<String> textos) {
  return List<AccionBingo>.generate(
    textos.length,
    (indice) => AccionBingo(
      id: '${prefijo}_$indice',
      texto: textos[indice],
    ),
  );
}

List<Deporte> crearCatalogoPredeterminado() {
  return <Deporte>[
    Deporte(
      id: 'futbol',
      nombre: 'Fútbol',
      claveIcono: 'futbol',
      acciones: _acciones('futbol', <String>[
        'Gol',
        'Tiro al arco',
        'Atajada del arquero',
        'Tiro de esquina',
        'Fuera de juego',
        'Tarjeta amarilla',
        'Tarjeta roja',
        'Falta cerca del área',
        'Penal cobrado',
        'Penal fallado',
        'Cambio de jugador',
        'Gol de cabeza',
        'Gol de tiro libre',
        'Remate al palo',
        'Asistencia',
        'Contraataque',
        'Saque lateral largo',
        'Revisión del VAR',
        'Lesión o atención médica',
        'Más de tres pases seguidos',
        'Recuperación en campo rival',
        'Despeje defensivo',
        'Celebración especial',
        'Remate desde fuera del área',
        'Empate momentáneo',
      ]),
    ),
    Deporte(
      id: 'basquetbol',
      nombre: 'Básquetbol',
      claveIcono: 'basquetbol',
      acciones: _acciones('basquetbol', <String>[
        'Triple',
        'Doble',
        'Tiro libre anotado',
        'Tiro libre fallado',
        'Rebote ofensivo',
        'Rebote defensivo',
        'Asistencia',
        'Robo de balón',
        'Tapón',
        'Pérdida de balón',
        'Falta personal',
        'Tiempo muerto',
        'Cambio de jugador',
        'Volcada',
        'Bandeja',
        'Canasta sobre la bocina',
        'Contraataque',
        'Falta ofensiva',
        'Balón fuera',
        'Salto entre dos',
        'Posesión de más de 20 segundos',
        'Defensa en zona',
        'Racha de seis puntos',
        'Empate en el marcador',
        'Prórroga',
      ]),
    ),
    Deporte(
      id: 'tenis',
      nombre: 'Tenis',
      claveIcono: 'tenis',
      acciones: _acciones('tenis', <String>[
        'Ace',
        'Doble falta',
        'Punto de quiebre',
        'Quiebre de servicio',
        'Devolución ganadora',
        'Error no forzado',
        'Pelota a la red',
        'Pelota fuera',
        'Rally de más de diez golpes',
        'Golpe ganador de derecha',
        'Golpe ganador de revés',
        'Volea ganadora',
        'Globo',
        'Dejada',
        'Passing shot',
        'Revisión electrónica',
        'Cambio de lado',
        'Juego en blanco',
        'Set point',
        'Match point',
        'Tie-break',
        'Pelota en la línea',
        'Primer servicio fallado',
        'Segundo servicio efectivo',
        'Remontada en un juego',
      ]),
    ),
    Deporte(
      id: 'running',
      nombre: 'Running',
      claveIcono: 'running',
      acciones: _acciones('running', <String>[
        'Completar 1 km',
        'Mantener ritmo objetivo',
        'Acelerar en una subida',
        'Recuperar en una bajada',
        'Superar una marca personal',
        'Tomar hidratación',
        'Pasar un punto de control',
        'Correr junto a un compañero',
        'Completar un sprint',
        'Mantener respiración controlada',
        'Cruzar un puente',
        'Correr por tierra',
        'Correr por asfalto',
        'Superar una pendiente',
        'Completar la mitad del recorrido',
        'Terminar sin detenerse',
        'Usar técnica de brazos',
        'Mantener postura estable',
        'Realizar calentamiento',
        'Realizar vuelta a la calma',
        'Completar 5 km',
        'Animar a otro corredor',
        'Pasar una señal de distancia',
        'Llegar a la meta',
        'Registrar el tiempo final',
      ]),
    ),
  ];
}
